//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InvatamSaCalculamModel", "FK_UserBigMedalUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvatamSaCalculam.Server.Models.User), "UserBigMedals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvatamSaCalculam.Server.Models.UserBigMedal), true)]
[assembly: EdmRelationshipAttribute("InvatamSaCalculamModel", "FK_UserCupUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvatamSaCalculam.Server.Models.User), "UserCups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvatamSaCalculam.Server.Models.UserCup), true)]
[assembly: EdmRelationshipAttribute("InvatamSaCalculamModel", "FK_UserGameUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvatamSaCalculam.Server.Models.User), "UserGames", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvatamSaCalculam.Server.Models.UserGame), true)]
[assembly: EdmRelationshipAttribute("InvatamSaCalculamModel", "FK_UserScoreUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvatamSaCalculam.Server.Models.User), "UserScores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvatamSaCalculam.Server.Models.UserScore), true)]
[assembly: EdmRelationshipAttribute("InvatamSaCalculamModel", "FK_UserSmallMedalUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvatamSaCalculam.Server.Models.User), "UserSmallMedals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvatamSaCalculam.Server.Models.UserSmallMedal), true)]

#endregion

namespace InvatamSaCalculam.Server.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InvatamSaCalculamEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InvatamSaCalculamEntities object using the connection string found in the 'InvatamSaCalculamEntities' section of the application configuration file.
        /// </summary>
        public InvatamSaCalculamEntities() : base("name=InvatamSaCalculamEntities", "InvatamSaCalculamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InvatamSaCalculamEntities object.
        /// </summary>
        public InvatamSaCalculamEntities(string connectionString) : base(connectionString, "InvatamSaCalculamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InvatamSaCalculamEntities object.
        /// </summary>
        public InvatamSaCalculamEntities(EntityConnection connection) : base(connection, "InvatamSaCalculamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserBigMedal> UserBigMedals
        {
            get
            {
                if ((_UserBigMedals == null))
                {
                    _UserBigMedals = base.CreateObjectSet<UserBigMedal>("UserBigMedals");
                }
                return _UserBigMedals;
            }
        }
        private ObjectSet<UserBigMedal> _UserBigMedals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserCup> UserCups
        {
            get
            {
                if ((_UserCups == null))
                {
                    _UserCups = base.CreateObjectSet<UserCup>("UserCups");
                }
                return _UserCups;
            }
        }
        private ObjectSet<UserCup> _UserCups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserGame> UserGames
        {
            get
            {
                if ((_UserGames == null))
                {
                    _UserGames = base.CreateObjectSet<UserGame>("UserGames");
                }
                return _UserGames;
            }
        }
        private ObjectSet<UserGame> _UserGames;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserScore> UserScores
        {
            get
            {
                if ((_UserScores == null))
                {
                    _UserScores = base.CreateObjectSet<UserScore>("UserScores");
                }
                return _UserScores;
            }
        }
        private ObjectSet<UserScore> _UserScores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserSmallMedal> UserSmallMedals
        {
            get
            {
                if ((_UserSmallMedals == null))
                {
                    _UserSmallMedals = base.CreateObjectSet<UserSmallMedal>("UserSmallMedals");
                }
                return _UserSmallMedals;
            }
        }
        private ObjectSet<UserSmallMedal> _UserSmallMedals;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserBigMedals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserBigMedals(UserBigMedal userBigMedal)
        {
            base.AddObject("UserBigMedals", userBigMedal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserCups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserCups(UserCup userCup)
        {
            base.AddObject("UserCups", userCup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserGames EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserGames(UserGame userGame)
        {
            base.AddObject("UserGames", userGame);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserScores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserScores(UserScore userScore)
        {
            base.AddObject("UserScores", userScore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSmallMedals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSmallMedals(UserSmallMedal userSmallMedal)
        {
            base.AddObject("UserSmallMedals", userSmallMedal);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static User CreateUser(global::System.Int32 id)
        {
            User user = new User();
            user.Id = id;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsTeacher
        {
            get
            {
                return _IsTeacher;
            }
            set
            {
                OnIsTeacherChanging(value);
                ReportPropertyChanging("IsTeacher");
                _IsTeacher = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTeacher");
                OnIsTeacherChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsTeacher;
        partial void OnIsTeacherChanging(Nullable<global::System.Boolean> value);
        partial void OnIsTeacherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TeacherId
        {
            get
            {
                return _TeacherId;
            }
            set
            {
                OnTeacherIdChanging(value);
                ReportPropertyChanging("TeacherId");
                _TeacherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherId");
                OnTeacherIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TeacherId;
        partial void OnTeacherIdChanging(Nullable<global::System.Int32> value);
        partial void OnTeacherIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserBigMedalUser", "UserBigMedals")]
        public EntityCollection<UserBigMedal> UserBigMedals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserBigMedal>("InvatamSaCalculamModel.FK_UserBigMedalUser", "UserBigMedals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserBigMedal>("InvatamSaCalculamModel.FK_UserBigMedalUser", "UserBigMedals", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserCupUser", "UserCups")]
        public EntityCollection<UserCup> UserCups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserCup>("InvatamSaCalculamModel.FK_UserCupUser", "UserCups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserCup>("InvatamSaCalculamModel.FK_UserCupUser", "UserCups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserGameUser", "UserGames")]
        public EntityCollection<UserGame> UserGames
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserGame>("InvatamSaCalculamModel.FK_UserGameUser", "UserGames");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserGame>("InvatamSaCalculamModel.FK_UserGameUser", "UserGames", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserScoreUser", "UserScores")]
        public EntityCollection<UserScore> UserScores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserScore>("InvatamSaCalculamModel.FK_UserScoreUser", "UserScores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserScore>("InvatamSaCalculamModel.FK_UserScoreUser", "UserScores", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserSmallMedalUser", "UserSmallMedals")]
        public EntityCollection<UserSmallMedal> UserSmallMedals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserSmallMedal>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "UserSmallMedals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserSmallMedal>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "UserSmallMedals", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="UserBigMedal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserBigMedal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserBigMedal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="goldMedals">Initial value of the GoldMedals property.</param>
        /// <param name="silverMedals">Initial value of the SilverMedals property.</param>
        /// <param name="bronzeMedals">Initial value of the BronzeMedals property.</param>
        public static UserBigMedal CreateUserBigMedal(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 goldMedals, global::System.Int32 silverMedals, global::System.Int32 bronzeMedals)
        {
            UserBigMedal userBigMedal = new UserBigMedal();
            userBigMedal.Id = id;
            userBigMedal.UserId = userId;
            userBigMedal.GoldMedals = goldMedals;
            userBigMedal.SilverMedals = silverMedals;
            userBigMedal.BronzeMedals = bronzeMedals;
            return userBigMedal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GoldMedals
        {
            get
            {
                return _GoldMedals;
            }
            set
            {
                OnGoldMedalsChanging(value);
                ReportPropertyChanging("GoldMedals");
                _GoldMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GoldMedals");
                OnGoldMedalsChanged();
            }
        }
        private global::System.Int32 _GoldMedals;
        partial void OnGoldMedalsChanging(global::System.Int32 value);
        partial void OnGoldMedalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SilverMedals
        {
            get
            {
                return _SilverMedals;
            }
            set
            {
                OnSilverMedalsChanging(value);
                ReportPropertyChanging("SilverMedals");
                _SilverMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SilverMedals");
                OnSilverMedalsChanged();
            }
        }
        private global::System.Int32 _SilverMedals;
        partial void OnSilverMedalsChanging(global::System.Int32 value);
        partial void OnSilverMedalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BronzeMedals
        {
            get
            {
                return _BronzeMedals;
            }
            set
            {
                OnBronzeMedalsChanging(value);
                ReportPropertyChanging("BronzeMedals");
                _BronzeMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BronzeMedals");
                OnBronzeMedalsChanged();
            }
        }
        private global::System.Int32 _BronzeMedals;
        partial void OnBronzeMedalsChanging(global::System.Int32 value);
        partial void OnBronzeMedalsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserBigMedalUser", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserBigMedalUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserBigMedalUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserBigMedalUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("InvatamSaCalculamModel.FK_UserBigMedalUser", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="UserCup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserCup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserCup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="addCup">Initial value of the AddCup property.</param>
        /// <param name="diffCup">Initial value of the DiffCup property.</param>
        /// <param name="divCup">Initial value of the DivCup property.</param>
        /// <param name="mulCup">Initial value of the MulCup property.</param>
        public static UserCup CreateUserCup(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 addCup, global::System.Int32 diffCup, global::System.Int32 divCup, global::System.Int32 mulCup)
        {
            UserCup userCup = new UserCup();
            userCup.Id = id;
            userCup.UserId = userId;
            userCup.AddCup = addCup;
            userCup.DiffCup = diffCup;
            userCup.DivCup = divCup;
            userCup.MulCup = mulCup;
            return userCup;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddCup
        {
            get
            {
                return _AddCup;
            }
            set
            {
                OnAddCupChanging(value);
                ReportPropertyChanging("AddCup");
                _AddCup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddCup");
                OnAddCupChanged();
            }
        }
        private global::System.Int32 _AddCup;
        partial void OnAddCupChanging(global::System.Int32 value);
        partial void OnAddCupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiffCup
        {
            get
            {
                return _DiffCup;
            }
            set
            {
                OnDiffCupChanging(value);
                ReportPropertyChanging("DiffCup");
                _DiffCup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiffCup");
                OnDiffCupChanged();
            }
        }
        private global::System.Int32 _DiffCup;
        partial void OnDiffCupChanging(global::System.Int32 value);
        partial void OnDiffCupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DivCup
        {
            get
            {
                return _DivCup;
            }
            set
            {
                OnDivCupChanging(value);
                ReportPropertyChanging("DivCup");
                _DivCup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivCup");
                OnDivCupChanged();
            }
        }
        private global::System.Int32 _DivCup;
        partial void OnDivCupChanging(global::System.Int32 value);
        partial void OnDivCupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MulCup
        {
            get
            {
                return _MulCup;
            }
            set
            {
                OnMulCupChanging(value);
                ReportPropertyChanging("MulCup");
                _MulCup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MulCup");
                OnMulCupChanged();
            }
        }
        private global::System.Int32 _MulCup;
        partial void OnMulCupChanging(global::System.Int32 value);
        partial void OnMulCupChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserCupUser", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserCupUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserCupUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserCupUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("InvatamSaCalculamModel.FK_UserCupUser", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="UserGame")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserGame : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserGame object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="hangman">Initial value of the Hangman property.</param>
        /// <param name="blocks">Initial value of the Blocks property.</param>
        public static UserGame CreateUserGame(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 hangman, global::System.Int32 blocks)
        {
            UserGame userGame = new UserGame();
            userGame.Id = id;
            userGame.UserId = userId;
            userGame.Hangman = hangman;
            userGame.Blocks = blocks;
            return userGame;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hangman
        {
            get
            {
                return _Hangman;
            }
            set
            {
                OnHangmanChanging(value);
                ReportPropertyChanging("Hangman");
                _Hangman = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hangman");
                OnHangmanChanged();
            }
        }
        private global::System.Int32 _Hangman;
        partial void OnHangmanChanging(global::System.Int32 value);
        partial void OnHangmanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Blocks
        {
            get
            {
                return _Blocks;
            }
            set
            {
                OnBlocksChanging(value);
                ReportPropertyChanging("Blocks");
                _Blocks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Blocks");
                OnBlocksChanged();
            }
        }
        private global::System.Int32 _Blocks;
        partial void OnBlocksChanging(global::System.Int32 value);
        partial void OnBlocksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserGameUser", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserGameUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserGameUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserGameUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("InvatamSaCalculamModel.FK_UserGameUser", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="UserScore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserScore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserScore object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        public static UserScore CreateUserScore(global::System.Int32 id, global::System.Int32 userId, global::System.Int64 score)
        {
            UserScore userScore = new UserScore();
            userScore.Id = id;
            userScore.UserId = userId;
            userScore.Score = score;
            return userScore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private global::System.Int64 _Score;
        partial void OnScoreChanging(global::System.Int64 value);
        partial void OnScoreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserScoreUser", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserScoreUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserScoreUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserScoreUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("InvatamSaCalculamModel.FK_UserScoreUser", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InvatamSaCalculamModel", Name="UserSmallMedal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserSmallMedal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserSmallMedal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="goldMedals">Initial value of the GoldMedals property.</param>
        /// <param name="silverMedals">Initial value of the SilverMedals property.</param>
        /// <param name="bronzeMedals">Initial value of the BronzeMedals property.</param>
        public static UserSmallMedal CreateUserSmallMedal(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 goldMedals, global::System.Int32 silverMedals, global::System.Int32 bronzeMedals)
        {
            UserSmallMedal userSmallMedal = new UserSmallMedal();
            userSmallMedal.Id = id;
            userSmallMedal.UserId = userId;
            userSmallMedal.GoldMedals = goldMedals;
            userSmallMedal.SilverMedals = silverMedals;
            userSmallMedal.BronzeMedals = bronzeMedals;
            return userSmallMedal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GoldMedals
        {
            get
            {
                return _GoldMedals;
            }
            set
            {
                OnGoldMedalsChanging(value);
                ReportPropertyChanging("GoldMedals");
                _GoldMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GoldMedals");
                OnGoldMedalsChanged();
            }
        }
        private global::System.Int32 _GoldMedals;
        partial void OnGoldMedalsChanging(global::System.Int32 value);
        partial void OnGoldMedalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SilverMedals
        {
            get
            {
                return _SilverMedals;
            }
            set
            {
                OnSilverMedalsChanging(value);
                ReportPropertyChanging("SilverMedals");
                _SilverMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SilverMedals");
                OnSilverMedalsChanged();
            }
        }
        private global::System.Int32 _SilverMedals;
        partial void OnSilverMedalsChanging(global::System.Int32 value);
        partial void OnSilverMedalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BronzeMedals
        {
            get
            {
                return _BronzeMedals;
            }
            set
            {
                OnBronzeMedalsChanging(value);
                ReportPropertyChanging("BronzeMedals");
                _BronzeMedals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BronzeMedals");
                OnBronzeMedalsChanged();
            }
        }
        private global::System.Int32 _BronzeMedals;
        partial void OnBronzeMedalsChanging(global::System.Int32 value);
        partial void OnBronzeMedalsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InvatamSaCalculamModel", "FK_UserSmallMedalUser", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("InvatamSaCalculamModel.FK_UserSmallMedalUser", "Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
