//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvatamSaCalculam.Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsTeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserBigMedal> UserBigMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserCup> UserCupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserGame> UserGamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserScore> UserScoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserSmallMedal> UserSmallMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsTeacher {
            get {
                return this.IsTeacherField;
            }
            set {
                if ((this.IsTeacherField.Equals(value) != true)) {
                    this.IsTeacherField = value;
                    this.RaisePropertyChanged("IsTeacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserBigMedal> UserBigMedals {
            get {
                return this.UserBigMedalsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBigMedalsField, value) != true)) {
                    this.UserBigMedalsField = value;
                    this.RaisePropertyChanged("UserBigMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserCup> UserCups {
            get {
                return this.UserCupsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCupsField, value) != true)) {
                    this.UserCupsField = value;
                    this.RaisePropertyChanged("UserCups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserGame> UserGames {
            get {
                return this.UserGamesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGamesField, value) != true)) {
                    this.UserGamesField = value;
                    this.RaisePropertyChanged("UserGames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserScore> UserScores {
            get {
                return this.UserScoresField;
            }
            set {
                if ((object.ReferenceEquals(this.UserScoresField, value) != true)) {
                    this.UserScoresField = value;
                    this.RaisePropertyChanged("UserScores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserSmallMedal> UserSmallMedals {
            get {
                return this.UserSmallMedalsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSmallMedalsField, value) != true)) {
                    this.UserSmallMedalsField = value;
                    this.RaisePropertyChanged("UserSmallMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserBigMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserCup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserGame))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserSmallMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.User))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserBigMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserCup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserGame))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserSmallMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.User))]
    public partial class EntityObject : InvatamSaCalculam.Client.ServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBigMedal", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserBigMedal : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BronzeMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SilverMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BronzeMedals {
            get {
                return this.BronzeMedalsField;
            }
            set {
                if ((this.BronzeMedalsField.Equals(value) != true)) {
                    this.BronzeMedalsField = value;
                    this.RaisePropertyChanged("BronzeMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoldMedals {
            get {
                return this.GoldMedalsField;
            }
            set {
                if ((this.GoldMedalsField.Equals(value) != true)) {
                    this.GoldMedalsField = value;
                    this.RaisePropertyChanged("GoldMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SilverMedals {
            get {
                return this.SilverMedalsField;
            }
            set {
                if ((this.SilverMedalsField.Equals(value) != true)) {
                    this.SilverMedalsField = value;
                    this.RaisePropertyChanged("SilverMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCup", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserCup : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddCupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiffCupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DivCupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MulCupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddCup {
            get {
                return this.AddCupField;
            }
            set {
                if ((this.AddCupField.Equals(value) != true)) {
                    this.AddCupField = value;
                    this.RaisePropertyChanged("AddCup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiffCup {
            get {
                return this.DiffCupField;
            }
            set {
                if ((this.DiffCupField.Equals(value) != true)) {
                    this.DiffCupField = value;
                    this.RaisePropertyChanged("DiffCup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivCup {
            get {
                return this.DivCupField;
            }
            set {
                if ((this.DivCupField.Equals(value) != true)) {
                    this.DivCupField = value;
                    this.RaisePropertyChanged("DivCup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MulCup {
            get {
                return this.MulCupField;
            }
            set {
                if ((this.MulCupField.Equals(value) != true)) {
                    this.MulCupField = value;
                    this.RaisePropertyChanged("MulCup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGame", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserGame : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HangmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Blocks {
            get {
                return this.BlocksField;
            }
            set {
                if ((this.BlocksField.Equals(value) != true)) {
                    this.BlocksField = value;
                    this.RaisePropertyChanged("Blocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hangman {
            get {
                return this.HangmanField;
            }
            set {
                if ((this.HangmanField.Equals(value) != true)) {
                    this.HangmanField = value;
                    this.RaisePropertyChanged("Hangman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserScore", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserScore : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSmallMedal", Namespace="http://schemas.datacontract.org/2004/07/InvatamSaCalculam.Server.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserSmallMedal : InvatamSaCalculam.Client.ServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BronzeMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SilverMedalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BronzeMedals {
            get {
                return this.BronzeMedalsField;
            }
            set {
                if ((this.BronzeMedalsField.Equals(value) != true)) {
                    this.BronzeMedalsField = value;
                    this.RaisePropertyChanged("BronzeMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoldMedals {
            get {
                return this.GoldMedalsField;
            }
            set {
                if ((this.GoldMedalsField.Equals(value) != true)) {
                    this.GoldMedalsField = value;
                    this.RaisePropertyChanged("GoldMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SilverMedals {
            get {
                return this.SilverMedalsField;
            }
            set {
                if ((this.SilverMedalsField.Equals(value) != true)) {
                    this.SilverMedalsField = value;
                    this.RaisePropertyChanged("SilverMedals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserBigMedal>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserBigMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserCup>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserCup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserGame>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserGame))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserScore>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.UserSmallMedal>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.UserSmallMedal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.RelatedEnd))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfUseroY1BxOq7", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfUseroY1BxOq7 : InvatamSaCalculam.Client.ServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7))]
    public partial class EntityReference : InvatamSaCalculam.Client.ServiceReference.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvatamSaCalculam.Client.ServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvatamSaCalculam.Client.ServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvatamSaCalculam.Client.ServiceReference.EntityReferenceOfUseroY1BxOq7))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Login", ReplyAction="http://tempuri.org/IServerService/LoginResponse")]
        System.Nullable<int> Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Register", ReplyAction="http://tempuri.org/IServerService/RegisterResponse")]
        bool Register(string username, string password, bool isTeacher, string teacherName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/IsTeacher", ReplyAction="http://tempuri.org/IServerService/IsTeacherResponse")]
        bool IsTeacher(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetScore", ReplyAction="http://tempuri.org/IServerService/GetScoreResponse")]
        long GetScore(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AddCup", ReplyAction="http://tempuri.org/IServerService/AddCupResponse")]
        void AddCup(string operationString, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/AddMedal", ReplyAction="http://tempuri.org/IServerService/AddMedalResponse")]
        void AddMedal(int puzzleSize, int medalType, int points, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetCup", ReplyAction="http://tempuri.org/IServerService/GetCupResponse")]
        int GetCup(string operationString, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetMedal", ReplyAction="http://tempuri.org/IServerService/GetMedalResponse")]
        int GetMedal(int puzzleSize, int medalType, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetTopPlayers", ReplyAction="http://tempuri.org/IServerService/GetTopPlayersResponse")]
        System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTopPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetBlocksScore", ReplyAction="http://tempuri.org/IServerService/GetBlocksScoreResponse")]
        int GetBlocksScore(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetHangmanScore", ReplyAction="http://tempuri.org/IServerService/GetHangmanScoreResponse")]
        int GetHangmanScore(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetBlocksScore", ReplyAction="http://tempuri.org/IServerService/SetBlocksScoreResponse")]
        void SetBlocksScore(int score, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetHangmanScore", ReplyAction="http://tempuri.org/IServerService/SetHangmanScoreResponse")]
        void SetHangmanScore(int score, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Reset", ReplyAction="http://tempuri.org/IServerService/ResetResponse")]
        void Reset(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetTeachers", ReplyAction="http://tempuri.org/IServerService/GetTeachersResponse")]
        System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTeachers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetTeachersStudents", ReplyAction="http://tempuri.org/IServerService/GetTeachersStudentsResponse")]
        System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTeachersStudents(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Delete", ReplyAction="http://tempuri.org/IServerService/DeleteResponse")]
        void Delete(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/CheckConnection", ReplyAction="http://tempuri.org/IServerService/CheckConnectionResponse")]
        void CheckConnection();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : InvatamSaCalculam.Client.ServiceReference.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<InvatamSaCalculam.Client.ServiceReference.IServerService>, InvatamSaCalculam.Client.ServiceReference.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<int> Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public bool Register(string username, string password, bool isTeacher, string teacherName) {
            return base.Channel.Register(username, password, isTeacher, teacherName);
        }
        
        public bool IsTeacher(int userId) {
            return base.Channel.IsTeacher(userId);
        }
        
        public long GetScore(int userId) {
            return base.Channel.GetScore(userId);
        }
        
        public void AddCup(string operationString, int userId) {
            base.Channel.AddCup(operationString, userId);
        }
        
        public void AddMedal(int puzzleSize, int medalType, int points, int userId) {
            base.Channel.AddMedal(puzzleSize, medalType, points, userId);
        }
        
        public int GetCup(string operationString, int userId) {
            return base.Channel.GetCup(operationString, userId);
        }
        
        public int GetMedal(int puzzleSize, int medalType, int userId) {
            return base.Channel.GetMedal(puzzleSize, medalType, userId);
        }
        
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTopPlayers() {
            return base.Channel.GetTopPlayers();
        }
        
        public int GetBlocksScore(int userId) {
            return base.Channel.GetBlocksScore(userId);
        }
        
        public int GetHangmanScore(int userId) {
            return base.Channel.GetHangmanScore(userId);
        }
        
        public void SetBlocksScore(int score, int userId) {
            base.Channel.SetBlocksScore(score, userId);
        }
        
        public void SetHangmanScore(int score, int userId) {
            base.Channel.SetHangmanScore(score, userId);
        }
        
        public void Reset(int userId) {
            base.Channel.Reset(userId);
        }
        
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTeachers() {
            return base.Channel.GetTeachers();
        }
        
        public System.Collections.Generic.List<InvatamSaCalculam.Client.ServiceReference.User> GetTeachersStudents(int teacherId) {
            return base.Channel.GetTeachersStudents(teacherId);
        }
        
        public void Delete(int userId) {
            base.Channel.Delete(userId);
        }
        
        public void CheckConnection() {
            base.Channel.CheckConnection();
        }
    }
}
